<a href="https://colab.research.google.com/github/AleR26/ColabFiles/blob/main/Practica_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Practica #6. Manejo de libreria Pandas

---

In [1]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/ClassFiles/titanic.csv')df.head()

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500

 Análisis de la distribución de supervivencia por combinación de sexo y clase del pasajero.

In [55]:
total = df['Age'].count()
#agrupar por clase, supervivencia y sexo para saber el total de cada grupo
sex_class = df.groupby(['Pclass','Sex','Survived']).agg({
    'Name' : 'count'
})
comb = (sex_class/total)*100
comb = comb.reset_index()
print(comb)

#Calculamos la mayor taza de supervivencia
supervivencia_alta = comb.loc[comb['Survived']== 1]
supervivencia_alta = comb.loc[supervivencia_alta['Name'].idxmax()]
print(f"Las personas de sexo {supervivencia_alta['Sex']} de la clase {supervivencia_alta['Pclass']} fueron las que tuvieron mayor taza de supervivencia.")

#Calculamos la menor taza de supervivencia
supervivencia_baja = comb.loc[comb['Survived']== 0]
supervivencia_baja = comb.loc[supervivencia_baja['Name'].idxmax()]
print(f"Las personas de sexo {supervivencia_baja['Sex']} de la clase {supervivencia_baja['Pclass']} fueron las que tuvieron menor taza de supervivencia.")

    Pclass     Sex  Survived       Name
0        1  female         0   0.338219
1        1  female         1  10.259301
2        1    male         0   8.680947
3        1    male         1   5.073281
4        2  female         0   0.676437
5        2  female         1   7.891770
6        2    male         0  10.259301
7        2    male         1   1.916573
8        3  female         0   8.117249
9        3  female         1   8.117249
10       3    male         0  33.370913
11       3    male         1   5.298760
Las personas de sexo female de la clase 1 fueron las que tuvieron mayor taza de supervivencia.
Las personas de sexo male de la clase 3 fueron las que tuvieron menor taza de supervivencia.

Identificación de familias grandes a bordo.

In [78]:
df['FamilySize'] = df[['Parents/Children Aboard','Siblings/Spouses Aboard']].sum(axis = 1)
familia_grande = df.loc[df['FamilySize'] > 3]
#El numero de pasajeros en familias grandes se muestra en el FamilySize
print(familia_grande)


super_familia_grande = familia_grande.groupby(['Survived']).agg({
    'FamilySize' : 'sum'
})
#Proporcion de supervivencia por familias grandes
comb = (super_familia_grande/total)*100
comb = comb.reset_index()
print(comb)

     Survived  Pclass                                               Name  \
7           0       3                      Master. Gosta Leonard Palsson
13          0       3                         Mr. Anders Johan Andersson
16          0       3                                Master. Eugene Rice
24          0       3                       Miss. Torborg Danira Palsson
25          1       3  Mrs. Carl Oscar (Selma Augusta Emilia Johansso...
..        ...     ...                                                ...
820         0       3                        Master. Urho Abraham Panula
842         0       3                            Mr. Douglas Bullen Sage
846         0       3             Master. Sigvard Harald Elias Andersson
859         0       3                           Miss. Dorothy Edith Sage
881         0       3                Mrs. William (Margaret Norton) Rice

        Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare  \
7      male   2.0                        3                        1  21.0750
13     male  39.0                        1                        5  31.2750
16     male   2.0                        4                        1  29.1250
24   female   8.0                        3                        1  21.0750
25   female  38.0                        1                        5  31.3875
..      ...   ...                      ...                      ...      ...
820    male   2.0                        4                        1  39.6875
842    male  18.0                        8                        2  69.5500
846    male   4.0                        4                        2  31.2750
859  female  14.0                        8                        2  69.5500
881  female  39.0                        0                        5  29.1250

     FamilySize
7             4
13            6
16            5
24            4
25            6
..          ...
820           5
842          10
846           6
859          10
881           5

[62 rows x 9 columns]
   Survived  FamilySize
0         0   34.160090
1         1    5.749718

Segmentación por grupos de edad.

In [88]:
import numpy as np

df['categoria_edad'] = np.where(df['Age'] > 18, 'Mayor de Edad', 'Menor de edad')
display(df.head())

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare,FamilySize,categoria_edad
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500,1,Mayor de Edad
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833,1,Mayor de Edad
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250,0,Mayor de Edad
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000,1,Mayor de Edad
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500,0,Mayor de Edad